### ISSUE TITLE
Traefik route config file disappears from (doesn't appear in the first place on) traefik filesystem

### ISSUE THREAD

**Issue by sed-i** [canonical/traefik-k8s-operator#111] opened 2022-12-08 17:31 UTC
### Bug Description

I deployed the load test with the "grafana workaround"
```
sudo -u ubuntu juju remove-relation grafana:ingress traefik
sleep 30
sudo -u ubuntu juju relate grafana:ingress traefik
```
after which grafana was reachable via ingress address.

After about 6 hours of operation, something went wrong (see logs section below), seems like all charms restarted, and grafana became unreachable.

Traefik still had grafana details in relation data,
```bash
$ juju show-unit traefik/0
```
```yaml
  - relation-id: 27
    endpoint: traefik-route
    related-endpoint: ingress
    application-data:
      config: |
        http:
          routers:
            juju-cos-lite-load-test-grafana-router:
              entryPoints:
              - web
              rule: PathPrefix(`/cos-lite-load-test-grafana`)
              service: juju-cos-lite-load-test-grafana-service
          services:
            juju-cos-lite-load-test-grafana-service:
              loadBalancer:
                servers:
                - url: http://grafana-0.grafana-endpoints.cos-lite-load-test.svc.cluster.local:3000/
```

But the config file is not on the filesystem (and curling the grafana endpoint gives 404):
```
ubuntu@pd-ssd-4cpu-8gb:~$ juju ssh --container traefik traefik/0 ls /opt/traefik/juju
juju_ingress_ingress-per-unit_4_prometheus.yaml
juju_ingress_ingress-per-unit_5_loki.yaml
juju_ingress_ingress_20_catalogue.yaml
juju_ingress_ingress_7_alertmanager.yaml
```
After re-relating `grafana:ingress traefik` the file re-appears:
```
ubuntu@pd-ssd-4cpu-8gb:~$ juju ssh --container traefik traefik/0 ls /opt/traefik/juju
juju_ingress_ingress-per-unit_4_prometheus.yaml
juju_ingress_ingress-per-unit_5_loki.yaml
juju_ingress_ingress_20_catalogue.yaml
juju_ingress_ingress_7_alertmanager.yaml
juju_ingress_traefik-route_28_grafana.yaml
```

### To Reproduce

Deploy the bundle (same thing happens on startup).

### Environment

Bundle from edge.

### Relevant log output

```shell
unit-grafana-0: 2022-12-08 01:02:25 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: write tcp 10.1.79.222:43324->10.152.183.132:17070: i/o timeout: write tcp 10.1.79.222:43324->10.152.183.132:17070: i/o timeout
unit-grafana-0: 2022-12-08 01:02:48 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: api connection broken unexpectedly

unit-traefik-0: 2022-12-08 01:05:02 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [40652e] "unit-traefik-0" cannot open api: try was stopped

unit-grafana-0: 2022-12-08 01:05:14 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [40652e] "unit-grafana-0" cannot open api: cannot resolve "controller-service.controller-uk8s.svc.cluster.local": lookup controller-service.controller-uk8s.svc.cluster.local: i/o timeout

unit-grafana-0: 2022-12-08 01:05:32 WARNING juju.worker.proxyupdater unable to set snap core settings [proxy.http= proxy.https= proxy.store=]: exec: "snap": executable file not found in $PATH, output: ""

unit-traefik-0: 2022-12-08 01:05:35 WARNING juju.worker.proxyupdater unable to set snap core settings [proxy.http= proxy.https= proxy.store=]: exec: "snap": executable file not found in $PATH, output: ""

unit-traefik-0: 2022-12-08 01:05:46 WARNING juju.worker.uniter.context could not retrieve the cloud API version: unable to determine legacy status for namespace cos-lite-load-test: Get "https://10.152.183.1:443/api/v1/namespaces/cos-lite-load-test": net/http: TLS handshake timeout
unit-grafana-0: 2022-12-08 01:05:46 WARNING juju.worker.uniter.context could not retrieve the cloud API version: unable to determine legacy status for namespace cos-lite-load-test: Get "https://10.152.183.1:443/api/v1/namespaces/cos-lite-load-test": net/http: TLS handshake timeout

unit-grafana-0: 2022-12-08 01:05:59 INFO unit.grafana/0.juju-log Running legacy hooks/start.
unit-traefik-0: 2022-12-08 01:05:59 INFO unit.traefik/0.juju-log Running legacy hooks/start.
```

**Comment by Abuelodelanada** [comment] 2023-08-21 19:26
I'm not able to reproduce the bug.

I deploy cos-lite using edge versions:

```shell
╭─ubuntu@charm-dev-juju-31 ~ [microk8s:cos]
╰─$ juju status                                      
Model  Controller  Cloud/Region        Version  SLA          Timestamp
cos    microk8s    microk8s/localhost  3.1.5    unsupported  15:50:58-03:00

App           Version  Status  Scale  Charm             Channel  Rev  Address         Exposed  Message
alertmanager  0.25.0   active      1  alertmanager-k8s  edge      86  10.152.183.156  no       
catalogue              active      1  catalogue-k8s     edge      22  10.152.183.242  no       
grafana       9.2.1    active      1  grafana-k8s       edge       0  10.152.183.18   no       
loki          2.7.4    active      1  loki-k8s          edge      96  10.152.183.107  no       
prometheus    2.46.0   active      1  prometheus-k8s    edge     138  10.152.183.235  no       
traefik       2.10.4   active      1  traefik-k8s       edge     143  192.168.1.250   no       

Unit             Workload  Agent  Address      Ports  Message
alertmanager/0*  active    idle   10.1.38.122         
catalogue/0*     active    idle   10.1.38.116         
grafana/0*       active    idle   10.1.38.67          
loki/0*          active    idle   10.1.38.66          
prometheus/0*    active    idle   10.1.38.81          
traefik/0*       active    idle   10.1.38.126    
```

And the config file is in the filesystem:

```shell
╭─ubuntu@charm-dev-juju-31 ~/repos/prometheus-k8s-operator ‹b9845d0› [microk8s:cos]
╰─$ juju ssh --container traefik traefik/0 ls -1 /opt/traefik/juju
juju_ingress_ingress-per-unit_28_prometheus.yaml
juju_ingress_ingress-per-unit_8_loki.yaml
juju_ingress_ingress_10_alertmanager.yaml
juju_ingress_ingress_23_catalogue.yaml
juju_ingress_traefik-route_9_grafana.yaml
```


In order to simulate "all charms restarted", I restarted the VM in which juju and microk8s are running, and after waiting for all the applications to come up again, all the files are in the filesystem:

```shell
╭─ubuntu@charm-dev-juju-31 ~ [microk8s:cos]
╰─$ juju ssh --container traefik traefik/0 ls -1 /opt/traefik/juju
juju_ingress_ingress-per-unit_28_prometheus.yaml
juju_ingress_ingress-per-unit_8_loki.yaml
juju_ingress_ingress_10_alertmanager.yaml
juju_ingress_ingress_23_catalogue.yaml
juju_ingress_traefik-route_9_grafana.yaml
```

Any ideas about this @sed-i ?

**Comment by PietroPasotti** [comment] 2023-09-21 11:12
I could see this happen once at some point, but it only happened the first time I removed a relation and added it back.
I wasn't able to repro after that.

My guess is either there's something going deeply wrong with the wipe-all-relations-and-restart-traefik, or it's the good old undead-relations juju bug.

**Comment by Abuelodelanada** [comment] 2023-09-29 19:17
I'm still not able to reproduce this issue.
Let's close it for now and keep an eye open on this.

**Closed by Abuelodelanada** 2023-09-29 19:17 UTC
Labels: Type: Bug, Status: Triage
