### ISSUE TITLE
Error description when deploying without metallb

### ISSUE THREAD

**Issue by zmraul** [canonical/traefik-k8s-operator#101] opened 2022-11-08 11:03 UTC
### Bug Description

When deploying the charm (from the COS bundle) without metallb enabled, the charm runs into an exception.

### To Reproduce

1. Enable only dns and hostpath-storage on microk8s
2. juju deploy cos-lite --channel edge --trust
- This deploys revision 93 of the `traefik-k8s` charm

### Environment

juju: 2.9.35 (bootstrapped agent: 2.9.29)
microk8s: 1.25.3

### Relevant log output

```shell
unit-traefik-0: 10:53:55 ERROR unit.traefik/0.juju-log traefik-route:5: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 710, in <module>
    main(TraefikIngressCharm)
  File "/var/lib/juju/agents/unit-traefik-0/charm/venv/ops/main.py", line 431, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-traefik-0/charm/venv/ops/main.py", line 142, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-traefik-0/charm/venv/ops/framework.py", line 316, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-traefik-0/charm/venv/ops/framework.py", line 784, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-traefik-0/charm/venv/ops/framework.py", line 857, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-traefik-0/charm/lib/charms/traefik_route_k8s/v0/traefik_route.py", line 166, in _on_relation_changed
    self._update_requirers_with_external_host()
  File "/var/lib/juju/agents/unit-traefik-0/charm/lib/charms/traefik_route_k8s/v0/traefik_route.py", line 175, in _update_requirers_with_external_host
    relation.data[self.charm.app]["external_host"] = self._stored.external_host
  File "/var/lib/juju/agents/unit-traefik-0/charm/venv/ops/model.py", line 945, in __setitem__
    raise RelationDataError('relation data values must be strings')
ops.model.RelationDataError: relation data values must be strings
unit-traefik-0: 10:53:55 ERROR juju.worker.uniter.operation hook "traefik-route-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-traefik-0: 10:53:55 INFO juju.worker.uniter awaiting error resolution for "relation-changed" hook
```

**Comment by PietroPasotti** [comment] 2022-11-08 16:36
Yeah, interesting. We were discussing this a few days ago. Not sure what the right way to solve this is. Ideally we'd have an assumes: metallb in the metadata, that'd feel cleanest.
On the charm side, the best we can do is catch this None and put the charm in blocked state with an useful message.

But at the same time I don't immediately see how the issue is directly related to the absence of metallb. The error is that external_hostname is not in stored data. How did the charm get there? Did you `config traefik external_hostname=foo.bar` beforehand?
Could you post the event sequence you're seeing?

**Comment by PietroPasotti** [comment] 2022-11-09 08:07
Also: https://github.com/canonical/traefik-route-k8s-operator/pull/18
closing as duplicate unless you can submit evidence that this is a different issue

**Closed** 2022-11-15 09:16 UTC
Labels: Type: Bug, Status: Triage
