### ISSUE TITLE
Sometimes two `yaml` config files are present for the same app

### ISSUE THREAD

**Issue by sed-i** [canonical/traefik-k8s-operator#225] opened 2023-08-19 04:41 UTC
### Bug Description

Occasionally, when removing a relation and then re-relating, the old config yaml remains on disk, such that after re-relate we have two yaml files, potentially different, causing "Internal error" etc.

### To Reproduce

On the `ingress` relation, remove relation and re-relate multiple times until it happens

### Environment

Juju 3.2, latest charms.

### Relevant log output

```shell
Don't have at hand.
```

**Comment by PietroPasotti** [comment] 2023-09-11 11:30
can repro with a simple scenario, working on a fix

**Comment by PietroPasotti** [comment] 2023-09-11 13:13
going at it for a half hour manually and I don't seem able to reproduce consistently

**Comment by lucabello** [comment] 2024-07-16 10:52
Closing because we can't reproduce this.

**Closed by lucabello** 2024-07-16 10:52 UTC
Labels: Type: Bug, Status: Triage
