### ISSUE TITLE
traefik in error state while adding relation

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/traefik-k8s-operator#31] opened 2022-03-23 23:00 UTC
### Bug Description

While adding relation between traefik and a charm using `ingress_per_unit` traefik end up in error state

### To Reproduce

1.- Deploy 2 units of loki charm
2.- Deploy traefik charm (`juju deploy ./traefik-k8s_ubuntu-20.04-amd64.charm traefik-ingress --trust --resource traefik-image=docker.io/jnsgruk/traefik:2.6.1`)
3. Add relation between both charms.

### Environment

- I built traefik charm from `main`.
- Using multipass workflow `charm-dev` 

### Relevant log output

```shell
unit-traefik-ingress-0: 19:49:05 INFO juju.worker.uniter awaiting error resolution for "relation-changed" hook
unit-traefik-ingress-0: 19:49:06 ERROR unit.traefik-ingress/0.juju-log ingress-per-unit:4: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 501, in <module>
    main(TraefikIngressCharm)
  File "/var/lib/juju/agents/unit-traefik-ingress-0/charm/venv/ops/main.py", line 426, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-traefik-ingress-0/charm/venv/ops/main.py", line 142, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-traefik-ingress-0/charm/venv/ops/framework.py", line 276, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-traefik-ingress-0/charm/venv/ops/framework.py", line 736, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-traefik-ingress-0/charm/venv/ops/framework.py", line 783, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-traefik-ingress-0/charm/venv/serialized_data_interface/relation.py", line 254, in _handle_relation
    self.on.ready.emit(event.relation)
  File "/var/lib/juju/agents/unit-traefik-ingress-0/charm/venv/ops/framework.py", line 276, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-traefik-ingress-0/charm/venv/ops/framework.py", line 736, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-traefik-ingress-0/charm/venv/ops/framework.py", line 783, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-traefik-ingress-0/charm/lib/charms/traefik_k8s/v0/ingress_per_unit.py", line 162, in _emit_request_event
    self.on.request.emit(event.relation)
  File "/var/lib/juju/agents/unit-traefik-ingress-0/charm/venv/ops/framework.py", line 276, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-traefik-ingress-0/charm/venv/ops/framework.py", line 736, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-traefik-ingress-0/charm/venv/ops/framework.py", line 783, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 241, in _handle_ingress_request
    self._process_ingress_relation(event.relation)
  File "./src/charm.py", line 273, in _process_ingress_relation
    config, unit_url = self._generate_per_unit_config(request, gateway_address, unit)
  File "./src/charm.py", line 300, in _generate_per_unit_config
    unit_name = request.get_unit_name(unit).replace("/", "-")
AttributeError: 'NoneType' object has no attribute 'replace'
```

### Additional context

juju status:

```
Model  Controller  Cloud/Region        Version  SLA          Timestamp
cos    charm-dev   microk8s/localhost  2.9.25   unsupported  19:51:34-03:00

App              Version  Status   Scale  Charm              Channel  Rev  Address         Exposed  Message
agent                     active       1  grafana-agent-k8s             1  10.152.183.172  no
loki                      active       2  loki-k8s                      0  10.152.183.98   no
traefik-ingress           waiting      1  traefik-k8s                   0  192.168.122.10  no       installing agent

Unit                Workload  Agent  Address       Ports  Message
agent/0*            active    idle   10.1.157.75       
loki/0*             active    idle   10.1.157.126       
loki/1              active    idle   10.1.157.108       
traefik-ingress/0*  error     idle   10.1.157.94          hook failed: "ingress-per-unit-relation-changed" for loki:ingress-per-unit

Relation provider                 Requirer                Interface         Type     Message
loki:logging                      agent:logging-consumer  loki_push_api     regular
loki:loki                         loki:loki               loki              peer
traefik-ingress:ingress-per-unit  loki:ingress-per-unit   ingress_per_unit  regular 
```

**Comment by mmanciop** [comment] 2022-03-24 16:31
@PietroPasotti could you please guard for this in #28 (if you haven't yet)?

**Comment by PietroPasotti** [comment] 2022-03-25 11:34
@mmanciop I did encounter this error, but I wasn't sure how to solve it. I'll try to reason through it.
Basically what happens is that the charm requests to generate per-unit config before the unit itself has shared (via ingress) the 'unit' name it wants to be addressed as. 
I saw some comments in code about UUIDs and why we can't simply do `unit.name`, but I didn't understand what that was about.

So given that this is done pretty much after any hook is run (_common_exit_hook style), would it make sense to skip all units for which the 'name' is unavailable in the databag, and rely on the fact that those units will eventually share their name and at that point we'll get another event and update the config?

**Comment by mmanciop** [comment] 2022-03-25 11:39
`unit.name` does not work as one would expect in cross-mode relations, try it. It’s a design decision from way back when.

I think that we could require the unit to put its name in the relation, and refuse to issue a URL otherwise.

**Comment by PietroPasotti** [comment] 2022-03-25 12:31
Oh right, was not thinking about cross-model relations. It makes sense since the same app could be deployed in different models and app/1 would then be ambiguous, I guess.

The unit is already required to put its name in the relation (the famous schema makes sure of that). That it isn't there means that the unit hasn't processed its relation-joined event yet.

**Comment by PietroPasotti** [comment] 2022-03-28 13:09
so that's a design change, right? 

Right now: traefik tries to determine the unit name from the relation.
Future: the unit itself shares via the relation the unit name it wishes to be addressed as, traefik uses it 'blindly'.

**Comment by PietroPasotti** [comment] 2022-03-28 13:11
> so that's a design change, right?
> 
> Right now: traefik tries to determine the unit name from the relation. Future: the unit itself shares via the relation the unit name it wishes to be addressed as, traefik uses it 'blindly'.

Would this be a 'defaulted' value, like: unit doesn't give me a name: let's try and guess it, or a required input?

**Comment by mmanciop** [comment] 2022-03-30 12:40
The proxied unit would need to declare its name before it is issued a URL and the associated route in Traefik.

**Comment by PietroPasotti** [comment] 2022-03-30 13:43
![image](https://user-images.githubusercontent.com/6230162/160848646-4bc26e60-2480-40ad-a81c-ad23023a3f0c.png)
Seems to work with the SDI-less version of ingress-per-unit, couldn't reproduce the bug.
And as far as I can see, the requirer already shares its unit's name to traefik. Might need to dig some more in the reason for this bug, I'm thinking it could be a race.

**Comment by simskij** [comment] 2022-05-26 11:30
I suggest closing this then and opening a new issue in case someone encounters it again with the SDI-less version. WDYT @PietroPasotti?

**Comment by PietroPasotti** [comment] 2022-05-27 11:05
Indeed. Closing for now.

**Closed by PietroPasotti** 2022-05-27 11:05 UTC
Labels: Type: Bug, Status: Triage
